# Generated by Django 5.2.8 on 2025-12-03 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('template_id', models.IntegerField(default=1)),
                ('name', models.CharField(default='Your Name', max_length=100)),
                ('tagline', models.CharField(default='Senior UX/UI Designer | Web Developer', max_length=200)),
                ('about_me', models.TextField(default='A short, compelling professional summary. Detail your key skills and professional goals here to introduce yourself.')),
                ('contact_email', models.EmailField(default='contact@example.com', max_length=254)),
                ('project_title_1', models.CharField(default='Project Title One: E-Commerce Redesign', max_length=150)),
                ('project_description_1', models.TextField(default='Designed and prototyped a new mobile shopping experience, resulting in a 30% increase in conversion.')),
                ('project_url_1', models.URLField(blank=True, default='#')),
                ('is_published', models.BooleanField(default=False)),
                ('published_url', models.CharField(default='sitelab.com/users/your-new-portfolio', max_length=255)),
            ],
        ),
    ]
