# Generated by Django 5.2.8 on 2025-12-04 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(help_text="FontAwesome class, e.g., 'fa-solid fa-camera'", max_length=100)),
                ('full_name', models.CharField(default='Samantha J. Doe', max_length=100)),
                ('tagline', models.CharField(default='Senior UX/UI Designer & Web Developer', max_length=255)),
                ('about_me', models.TextField(default='A seasoned professional dedicated to crafting visually stunning and highly functional digital experiences.')),
                ('contact_email', models.EmailField(default='contact@samanthajdoe.com', max_length=254)),
                ('project_title', models.CharField(default='Sample Project', max_length=255)),
                ('project_description', models.TextField(default='A sample project description to showcase the template layout.')),
                ('project_url', models.URLField(default='https://example.com', help_text='Example project link', max_length=255)),
                ('template_path', models.CharField(default='portfolios/portfolio_template1.html', help_text='Path to the HTML template', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='about_me',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='name',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='project_description_1',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='project_title_1',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='project_url_1',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='published_url',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='tagline',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='template_id',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='portfolio', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolios', to='portfolios.portfoliotemplate'),
        ),
    ]
