# Generated by Django 5.2.8 on 2025-12-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_portfoliotemplate_remove_portfolio_about_me_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliotemplate',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
