# Generated by Django 5.2.8 on 2025-12-03 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('project_type', models.CharField(choices=[('website', 'Website'), ('mobile_app', 'Mobile App'), ('branding', 'Branding'), ('other', 'Other')], max_length=50)),
                ('project_focus', models.CharField(choices=[('design', 'Design'), ('development', 'Development'), ('marketing', 'Marketing'), ('other', 'Other')], max_length=50)),
                ('budget_range', models.CharField(choices=[('<500', 'Less than $500'), ('500-1000', '$500 - $1000'), ('1000-5000', '$1000 - $5000'), ('>5000', 'More than $5000')], max_length=50)),
                ('project_title', models.CharField(max_length=200)),
                ('requirements', models.TextField()),
                ('sample_links', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
